tap_install:
  version:
    package_repo_bundle_tag: "1.5.0-rc.13"
    package_version: "1.5.0-rc.13"
  package_repository:
    oci_repository: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages
